name: Erlang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        erlang_version:
        - "23.3"
        - "24.1"
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: CONFIGURE ERLANG
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.erlang_version }}
    - name: BUILD
      run: make
    - name: CHECK
      run: make check

  build-bazel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp_major:
        - "24"
        - "25"
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: TEST
      run: |
        bazelisk test //... --config=rbe-${{ matrix.otp_major }}
